config/routes.rb
Rails.application.routes.draw do
  get 'event_registrations/stats', to: 'event_registrations#stats', as: 'event_registrations_stats'

  resources :event_registrations, only: [:index, :show, :new, :create]

  resources :events, only: [:index, :show]

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  root 'event_registrations#new'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :event_registrations

  validates :name, :registration_fee, presence: true
end

app/models/event_registration.rb
class EventRegistration < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :events

  validates :name, :college, :token, :amount, :events, presence: true
  validates :token, uniqueness: true

  validates_presence_of :user
  validates_associated :user

  validates_format_of :mobile_no, with: /\A\d{10}\z/, message: "is of an invalid format. 10 digit mobile number only."
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable,
         :trackable, :validatable, :registerable

  has_many :event_registrations

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_total_due, if: :user_signed_in?

  private

    def set_total_due
      @total_due = calculate_total_due(current_user)
    end

    def calculate_total_due(user)
      sum = 0
      EventRegistration.where(user: user).each do |r|
        sum += r.amount
      end

      return sum
    end
end

app/controllers/event_registrations_controller.rb
class EventRegistrationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recent_registrations, only: [:new, :create]

  # GET /event_registrations
  def index
    @event_registrations = EventRegistration.order('created_at DESC')
  end

  # GET /event_registrations/1
  def show
    @event_registration = EventRegistration.find(params[:id])
  end

  # GET /event_registrations/new
  def new
    if current_user.valid_password? current_user.email
      flash.now[:alert] = "Please change your password"
    end

    @event_registration = EventRegistration.new

    @events = Event.all
    render :new
  end

  # POST /event_registrations
  def create
    @event_registration = EventRegistration.new(event_registration_params)

    @event_registration.token = loop do
      t = SecureRandom.hex(3)
      break t unless EventRegistration.exists?(token: t)
    end

    @event_registration.amount = registration_total_fee()
    @event_registration.user = current_user
    @event_registration.events = registered_events()

    if @event_registration.save
      SMSSender.send_sms(
        @event_registration.mobile_no,
        sms_message
      )

      redirect_to @event_registration, notice: 'Event registration was successfully created.'
    else
      @events = Event.all
      render :new
    end
  end

  def stats
    @user_dues = []
    @total_collected = 0
    User.find_each do |u|
      due = calculate_total_due(u)
      @user_dues << {name: u.name, due: due}
      @total_collected += due
    end
    @user_dues = @user_dues.sort_by { |u| u[:due]}.reverse
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def registration_total_fee
      if not params["events"]
        return 0
      end
      sum = 0
      params["events"].each do |event_code|
        next if event_code == "none"
        sum += Event.where(name: event_code).first.registration_fee
      end

      return sum
    end

    def registered_events
      if not params["events"]
        return []
      end
      events = []
      params["events"].each do |event_code|
        next if event_code == "none"
        events << Event.where(name: event_code).first
      end

      return events
    end

    def sms_message
      events = @event_registration.events.map(&:pretty_name).join(', ')
      m = "Dear #{@event_registration.name}, your registration of Rs. #{@event_registration.amount} for #{events} at Utsaha 2015 has been confirmed. UniqueToken: #{@event_registration.token}. Please keep this token safely."

      if @event_registration.events.any? { |e| e.name.include? "tshirt" }
        m << " Collect T-Shirts on 18th Noon at the Main Block."
      end

      # Send only ASCII characters in SMS because Kishan is scared
      # that it might break their API. :P
      encoding_options = {
        :invalid           => :replace,  # Replace invalid byte sequences
        :undef             => :replace,  # Replace anything not defined in ASCII
        :replace           => '',        # Use a blank for those replacements
        :universal_newline => true       # Always break lines with \n
      }
      return m.encode(Encoding.find('ASCII'), encoding_options)
    end

    # Only allow a trusted parameter "white list" through.
    def event_registration_params
      params.require(:event_registration).permit(:name, :mobile_no, :college, :events)
    end

    def set_recent_registrations
      @recent_registrations = EventRegistration.order(id: :desc).limit(5)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_registrations_helper.rb
module EventRegistrationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_registrations/_form.html.erb
<%= form_for(@event_registration) do |f| %>
  <% if @event_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_registration.errors.count, "error") %> prohibited this event_registration from being saved:</h2>

      <ul>
      <% @event_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_registrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Event Registrations</h1>

<table class="statistics table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile no</th>
      <th>College</th>
      <th>Token</th>
      <th>Amount</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_registrations.each do |event_registration| %>
      <tr>
        <td><%= event_registration.name %></td>
        <td><%= event_registration.mobile_no %></td>
        <td><%= event_registration.college %></td>
        <td><%= event_registration.token %></td>
        <td><%= event_registration.amount %></td>
        <td><%= event_registration.user.name %></td>
        <td><%= link_to 'Show', event_registration %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event registration', new_event_registration_path %>

app/views/event_registrations/new.html.erb
<main>
  <div class="container">
    <div class="col-lg-6 col-md-6">

      <%= form_for(@event_registration) do |f| %>
        <% if @event_registration.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@event_registration.errors.count, "error") %> prohibited this event_registration from being saved:</h2>

            <ul>
              <% @event_registration.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, {class: "form-control", placeholder: "Enter name"} %>
        </div>
        <div class="form-group">
          <%= f.label :mobile_number %><br>
          <%= f.text_field :mobile_no, {class: "form-control", placeholder: "Mobile Number"} %>
        </div>
        <div class="form-group">
          <%= f.label :college_name %><br>
          <%= f.text_field :college, {class: "form-control", placeholder: "College"} %>
        </div>

        <div class="form-group" id="select-fields">
          <h5><b>Events</b></h5>
        </div>

        <div id="add-event-link">
          <a href="#" class="btn btn-default">Add An Event</a>
        </div>

        <br>

        <div id="total-container" class="well">Collect INR 0</div>

        <br>
        <div class="actions">
          <%= f.submit "Go", {class: "btn btn-default"} %>
        </div>
      <% end %>
    </div>

    <div class="col-lg-6 col-md-6">

      <div class="panel panel-default">
        <div class="panel-heading">
          Recent Registrations
        </div>
        <div class="panel-body">

          <table class="table">
            <thead>
              <tr>
                <th>Token</th>
                <th>Name</th>
                <th>College</th>
                <th>Event</th>
                <th>Amount</th>
              </tr>
            </thead>
            <% @recent_registrations.each do |reg| %>
              <tr>
                <td><%= reg.token %></td>
                <td><%= reg.name %></td>
                <td><%= reg.college %></td>
                <td>
                  <% reg.events.each.with_index do |e, i| %>
                    <%= " | " unless i == 0 %><%= e.pretty_name %>
                  <% end%>
                </td>
                <td><%= reg.amount %></td>
              </tr>
            <% end %>
          </table>

        </div>
      </div>

    </div>
  </div>
</main>

<script type="text/javascript">
 var events = [{
   name: 'none',
   pretty_name: "None",
   fee: 0
 }<% @events.each do |event| %> ,
 {
   name: "<%= event.name %>",
   pretty_name: "<%= event.pretty_name %>",
   fee: <%= event.registration_fee %>
            }
 <% end %>
 ];

 var selectNewEvent;
 var total = 0;
 var i;
 var option;
 var len = events.length;
 var addEventLink = document.querySelector('#add-event-link');
 var selectFields = document.querySelector('#select-fields');
 var totalContainer = document.querySelector('#total-container');
 selectFields.style.display = "none";

 addEventLink.addEventListener('click', function(e) {
   e.preventDefault();
   selectNewEvent = document.createElement('select');
   selectNewEvent.className = "form-control";
   selectNewEvent.name = "events[]";
   selectFields.appendChild(selectNewEvent);
   for (i = 0; i < len; i++) {
     option = document.createElement("option");
     option.value = events[i].name;
     option.text = events[i].pretty_name + ", INR " + events[i].fee;
     $(option).data('fee', events[i].fee);
     selectNewEvent.appendChild(option);
   }
   $(selectNewEvent).select2();
   selectFields.style.display = "block";
 });
 $('form').on('change', function () {
   var total = $('select option:selected').toArray().reduce(function (p, c, v) {
     return p + $(c).data('fee');
   }, 0);
   totalContainer.innerHTML = "Collect INR " + total;
 });
</script>

app/views/event_registrations/show.html.erb
<main>
  <div class="container">
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">

      <h1 class="text-center">Event Registration</h1>

      <table class="table table-bordered table-condensed">
        <tr>
          <td><strong>Name</strong></td>
          <td><%= @event_registration.name %></td>
        </tr>

        <tr>
          <td><strong>Mobile no</strong></td>
          <td><%= @event_registration.mobile_no %></td>
        </tr>

        <tr>
          <td><strong>College</strong></td>
          <td><%= @event_registration.college %></td>
        </tr>

        <tr>
          <td><strong>Token</strong></td>
          <td><strong><%= @event_registration.token %></strong></td>
        </tr>

        <tr>
          <td><strong>Events</strong></td>
          <td>
            <% @event_registration.events.each.with_index do |e, i| %>
              <%= " | " unless i == 0 %><%= e.pretty_name %>
            <% end %>
          </td>
        </tr>

        <tr>
          <td><strong>Amount</strong></td>
          <td><strong><%= @event_registration.amount %></strong></td>
        </tr>

        <tr>
          <td><strong>User</strong></td>
          <td><%= @event_registration.user.name %></td>
        </tr>

        <tr>
          <td><strong>Time</strong></td>
          <td><%= @event_registration.created_at.in_time_zone("Kolkata") %></td>
        </tr>
      </table>
      <%= link_to 'Back', event_registrations_path %>
    </div>
  </div>
</main>

app/views/event_registrations/stats.html.erb
<p id="notice"><%= notice %></p>

<h1>Total Collected per User</h1>

<table class="statistics table">
  <thead>
    <tr>
      <th>User</th>
      <th>Collected</th>
    </tr>
  </thead>

  <tbody>
    <% @user_dues.each do |u| %>
      <tr>
        <td><%= u[:name] %></td>
        <td><%= u[:due] %></td>
      </tr>
    <% end %>
    <tr>
      <td><h2>Total Collected</h2></td>
      <td><h2><%= @total_collected %></h2></td>
    </tr>
  </tbody>
</table>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event List</h1>

<table class="statistics table">
  <thead>
    <tr>
      <th>Event Name</th>
      <th>No. of Registrations</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.pretty_name %></td>
        <td><%= event.event_registrations.count %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/show.html.erb
<main>
  <div class="container">
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">

      <h1 class="text-center"><%= @event.pretty_name %> Registrations</h1>

      <table class="table table-bordered table-condensed">
        <thead>
          <tr>
            <th>Token</th>
            <th>Name</th>
            <th>Mobile No.</th>
            <th>College</th>
          </tr>
        </thead>
        <tbody>

          <% @event.event_registrations.find_each do |er| %>
          <tr>
            <td><%= er.token %></td>
            <td><%= er.name %></td>
            <td><%= er.mobile_no %></td>
            <td><%= er.college %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
      <%= link_to 'Back', events_path %>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Utsaha 2015 Registration</title>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Select2 -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.1/css/select2.min.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
     .select2.select2-container.select2-container--default {
       width: 100% !important;
       margin-top: 10px;
     }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.1/js/select2.min.js"></script>

  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">

  	<div class="navbar-header">
  	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar">
  	    <span class="sr-only">Toggle navigation</span>
  	    <span class="icon-bar"></span>
  	    <span class="icon-bar"></span>
  	    <span class="icon-bar"></span>
  	  </button>
  	  <a class="navbar-brand" href="/">Utsaha 2015 Registrations</a>
  	</div>

  	<div class="collapse navbar-collapse" id="main-navbar">
  	  <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
	    <li>
	      <%= link_to "Change your password", edit_user_registration_path %>
	    </li>
            <% end %>
            <li>
              <a href="#" id="print-page">Print</a>
            </li>
            <li>
	      <%= link_to "All Registrations", event_registrations_path %>
            </li>
            <li>
              <%= link_to "Events", events_path %>
            </li>
            <li>
              <%= link_to "Stats", event_registrations_stats_path %>
            </li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logged in as <strong><%= current_user.name %></strong> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Total Due: INR <%= @total_due %></a></li>
                  <li class="divider"></li>
                  <li><%= link_to "Signout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
  	  </ul>
  	</div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <script type="text/javascript">
     var printPage = document.querySelector('#print-page');
     printPage.addEventListener('click', function(e) {
       e.preventDefault();
       window.print();
     });
    </script>

  </body>
</html>